USE DATABASE ECOMMERCE_DB;

USE SCHEMA RAW;

CREATE OR REPLACE TABLE ECOMMERCE_DB.RAW.ANALYTICS_ORDERS (

    ORDER_ID NUMBER,
    CUSTOMER_NAME STRING,
    ITEM_NAME STRING,
    PRICE NUMBER,

    INSERTED_AT TIMESTAMP_NTZ
    DEFAULT CURRENT_TIMESTAMP()

);