SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT ORDER_ID) AS unique_orders
FROM ECOMMERCE_DB.RAW.ANALYTICS_ORDERS;

SELECT ORDER_ID, COUNT(*)
FROM ECOMMERCE_DB.RAW.ANALYTICS_ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;