CREATE OR REPLACE TABLE ECOMMERCE_DB.RAW.FINAL_SALES_REPORT AS

SELECT

    O.ORDER_ID,
    O.ITEM_NAME,
    O.PRICE,

    C.CUSTOMER_NAME,
    C.EMAIL,
    C.COUNTRY

FROM ECOMMERCE_DB.RAW.ORDERS O

JOIN ECOMMERCE_DB.RAW.CUSTOMERS C

ON O.CUSTOMER_NAME = C.CUSTOMER_NAME;