CREATE DATABASE ECOMMERCE_DB;

USE ECOMMERCE_DB;

CREATE SCHEMA RAW;

USE SCHEMA RAW;

CREATE OR REPLACE STAGE my_s3_stage
URL = 's3://s3-ecommerce-raw-data-landing/'
STORAGE_INTEGRATION = s3_integration;

LIST @my_s3_stage;

CREATE OR REPLACE TABLE ECOMMERCE_DB.RAW.ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_NAME STRING,
    ITEM_NAME STRING,
    PRICE NUMBER
);

CREATE OR REPLACE TABLE ECOMMERCE_DB.RAW.CUSTOMERS (
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING
);