CREATE OR REPLACE STORAGE INTEGRATION s3_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = ('s3://s3-ecommerce-raw-data-landing/')
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::452596137450:role/Kinesis-Agent-Role-Ecommerce';