CREATE OR REPLACE PIPE ECOMMERCE_DB.RAW.ORDERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ECOMMERCE_DB.RAW.ORDERS
FROM @my_s3_stage/orders/
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
);

CREATE OR REPLACE PIPE ECOMMERCE_DB.RAW.CUSTOMERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ECOMMERCE_DB.RAW.CUSTOMERS
FROM @my_s3_stage/customers/
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
);

SHOW PIPES;