CREATE OR REPLACE SCHEMA ANALYTICS;

USE SCHEMA ANALYTICS;

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE SYSADMIN;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE SYSADMIN;

GRANT CREATE TABLE ON SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE SYSADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES
IN SCHEMA ECOMMERCE_DB.ANALYTICS
TO ROLE SYSADMIN;